# Generated by Django 6.0.7 on 2026-07-18 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.CharField(max_length=500)),
                ('sendat', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tahun', models.IntegerField()),
                ('universitas', models.CharField(max_length=50)),
                ('cerita', models.CharField(max_length=100)),
                ('jurusan', models.CharField(max_length=50)),
                ('lulusan', models.CharField(max_length=50)),
                ('tempat', models.CharField(max_length=50)),
                ('is_true', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tahun', models.IntegerField()),
                ('posisi', models.CharField(max_length=50)),
                ('di', models.CharField(max_length=50)),
                ('kota', models.CharField(max_length=50)),
                ('cerita', models.CharField(max_length=200)),
                ('show', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50)),
                ('desk', models.CharField(max_length=50)),
            ],
        ),
    ]
