# Generated by Django 6.0.7 on 2026-07-23 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('porto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='fitur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fiturapp', models.CharField(max_length=100)),
                ('nama', models.CharField(max_length=100)),
                ('project', models.CharField(max_length=100)),
                ('about', models.TextField()),
                ('bahasa', models.CharField(max_length=255)),
            ],
        ),
    ]
