# Generated by Django 6.0.7 on 2026-07-25 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('porto', '0002_fitur'),
    ]

    operations = [
        migrations.CreateModel(
            name='setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintance', models.BooleanField(default=False)),
            ],
        ),
    ]
